[2024-05-14T19:56:32.595+0000] {processor.py:161} INFO - Started process (PID=168) to work on /opt/airflow/dags/DE_DP_dag.py
[2024-05-14T19:56:32.596+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/DE_DP_dag.py for tasks to queue
[2024-05-14T19:56:32.599+0000] {logging_mixin.py:188} INFO - [2024-05-14T19:56:32.598+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/DE_DP_dag.py
[2024-05-14T19:56:32.618+0000] {logging_mixin.py:188} INFO - [2024-05-14T19:56:32.613+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/DE_DP_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DE_DP_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-05-14T19:56:32.620+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/DE_DP_dag.py
[2024-05-14T19:56:32.650+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/DE_DP_dag.py took 0.061 seconds
[2024-05-14T19:57:02.789+0000] {processor.py:161} INFO - Started process (PID=173) to work on /opt/airflow/dags/DE_DP_dag.py
[2024-05-14T19:57:02.790+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/DE_DP_dag.py for tasks to queue
[2024-05-14T19:57:02.792+0000] {logging_mixin.py:188} INFO - [2024-05-14T19:57:02.791+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/DE_DP_dag.py
[2024-05-14T19:57:02.808+0000] {logging_mixin.py:188} INFO - [2024-05-14T19:57:02.804+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/DE_DP_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DE_DP_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-05-14T19:57:02.809+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/DE_DP_dag.py
[2024-05-14T19:57:02.848+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/DE_DP_dag.py took 0.066 seconds
[2024-05-14T19:57:32.966+0000] {processor.py:161} INFO - Started process (PID=178) to work on /opt/airflow/dags/DE_DP_dag.py
[2024-05-14T19:57:32.967+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/DE_DP_dag.py for tasks to queue
[2024-05-14T19:57:32.969+0000] {logging_mixin.py:188} INFO - [2024-05-14T19:57:32.969+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/DE_DP_dag.py
[2024-05-14T19:57:32.991+0000] {logging_mixin.py:188} INFO - [2024-05-14T19:57:32.986+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/DE_DP_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DE_DP_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-05-14T19:57:32.992+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/DE_DP_dag.py
[2024-05-14T19:57:33.020+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/DE_DP_dag.py took 0.060 seconds
[2024-05-14T19:58:03.168+0000] {processor.py:161} INFO - Started process (PID=183) to work on /opt/airflow/dags/DE_DP_dag.py
[2024-05-14T19:58:03.169+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/DE_DP_dag.py for tasks to queue
[2024-05-14T19:58:03.171+0000] {logging_mixin.py:188} INFO - [2024-05-14T19:58:03.171+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/DE_DP_dag.py
[2024-05-14T19:58:03.191+0000] {logging_mixin.py:188} INFO - [2024-05-14T19:58:03.186+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/DE_DP_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DE_DP_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-05-14T19:58:03.192+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/DE_DP_dag.py
[2024-05-14T19:58:03.218+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/DE_DP_dag.py took 0.055 seconds
[2024-05-14T19:58:33.337+0000] {processor.py:161} INFO - Started process (PID=188) to work on /opt/airflow/dags/DE_DP_dag.py
[2024-05-14T19:58:33.338+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/DE_DP_dag.py for tasks to queue
[2024-05-14T19:58:33.340+0000] {logging_mixin.py:188} INFO - [2024-05-14T19:58:33.339+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/DE_DP_dag.py
[2024-05-14T19:58:33.359+0000] {logging_mixin.py:188} INFO - [2024-05-14T19:58:33.356+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/DE_DP_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DE_DP_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-05-14T19:58:33.361+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/DE_DP_dag.py
[2024-05-14T19:58:33.387+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/DE_DP_dag.py took 0.056 seconds
[2024-05-14T19:59:03.530+0000] {processor.py:161} INFO - Started process (PID=193) to work on /opt/airflow/dags/DE_DP_dag.py
[2024-05-14T19:59:03.531+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/DE_DP_dag.py for tasks to queue
[2024-05-14T19:59:03.533+0000] {logging_mixin.py:188} INFO - [2024-05-14T19:59:03.533+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/DE_DP_dag.py
[2024-05-14T19:59:03.553+0000] {logging_mixin.py:188} INFO - [2024-05-14T19:59:03.549+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/DE_DP_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DE_DP_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-05-14T19:59:03.554+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/DE_DP_dag.py
[2024-05-14T19:59:03.580+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/DE_DP_dag.py took 0.055 seconds
[2024-05-14T19:59:33.701+0000] {processor.py:161} INFO - Started process (PID=198) to work on /opt/airflow/dags/DE_DP_dag.py
[2024-05-14T19:59:33.702+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/DE_DP_dag.py for tasks to queue
[2024-05-14T19:59:33.704+0000] {logging_mixin.py:188} INFO - [2024-05-14T19:59:33.704+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/DE_DP_dag.py
[2024-05-14T19:59:33.721+0000] {logging_mixin.py:188} INFO - [2024-05-14T19:59:33.717+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/DE_DP_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DE_DP_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-05-14T19:59:33.722+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/DE_DP_dag.py
[2024-05-14T19:59:33.749+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/DE_DP_dag.py took 0.053 seconds
[2024-05-14T20:00:03.896+0000] {processor.py:161} INFO - Started process (PID=203) to work on /opt/airflow/dags/DE_DP_dag.py
[2024-05-14T20:00:03.897+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/DE_DP_dag.py for tasks to queue
[2024-05-14T20:00:03.898+0000] {logging_mixin.py:188} INFO - [2024-05-14T20:00:03.898+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/DE_DP_dag.py
[2024-05-14T20:00:03.917+0000] {logging_mixin.py:188} INFO - [2024-05-14T20:00:03.913+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/DE_DP_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DE_DP_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-05-14T20:00:03.918+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/DE_DP_dag.py
[2024-05-14T20:00:03.944+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/DE_DP_dag.py took 0.054 seconds
[2024-05-14T20:00:34.067+0000] {processor.py:161} INFO - Started process (PID=208) to work on /opt/airflow/dags/DE_DP_dag.py
[2024-05-14T20:00:34.068+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/DE_DP_dag.py for tasks to queue
[2024-05-14T20:00:34.070+0000] {logging_mixin.py:188} INFO - [2024-05-14T20:00:34.070+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/DE_DP_dag.py
[2024-05-14T20:00:34.087+0000] {logging_mixin.py:188} INFO - [2024-05-14T20:00:34.083+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/DE_DP_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DE_DP_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-05-14T20:00:34.089+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/DE_DP_dag.py
[2024-05-14T20:00:34.115+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/DE_DP_dag.py took 0.053 seconds
[2024-05-14T20:01:04.257+0000] {processor.py:161} INFO - Started process (PID=213) to work on /opt/airflow/dags/DE_DP_dag.py
[2024-05-14T20:01:04.258+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/DE_DP_dag.py for tasks to queue
[2024-05-14T20:01:04.260+0000] {logging_mixin.py:188} INFO - [2024-05-14T20:01:04.260+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/DE_DP_dag.py
[2024-05-14T20:01:04.277+0000] {logging_mixin.py:188} INFO - [2024-05-14T20:01:04.273+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/DE_DP_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DE_DP_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-05-14T20:01:04.278+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/DE_DP_dag.py
[2024-05-14T20:01:04.305+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/DE_DP_dag.py took 0.053 seconds
[2024-05-14T20:01:34.458+0000] {processor.py:161} INFO - Started process (PID=218) to work on /opt/airflow/dags/DE_DP_dag.py
[2024-05-14T20:01:34.459+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/DE_DP_dag.py for tasks to queue
[2024-05-14T20:01:34.461+0000] {logging_mixin.py:188} INFO - [2024-05-14T20:01:34.461+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/DE_DP_dag.py
[2024-05-14T20:01:34.476+0000] {logging_mixin.py:188} INFO - [2024-05-14T20:01:34.473+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/DE_DP_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DE_DP_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-05-14T20:01:34.477+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/DE_DP_dag.py
[2024-05-14T20:01:34.503+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/DE_DP_dag.py took 0.051 seconds
[2024-05-14T20:02:04.630+0000] {processor.py:161} INFO - Started process (PID=223) to work on /opt/airflow/dags/DE_DP_dag.py
[2024-05-14T20:02:04.631+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/DE_DP_dag.py for tasks to queue
[2024-05-14T20:02:04.633+0000] {logging_mixin.py:188} INFO - [2024-05-14T20:02:04.633+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/DE_DP_dag.py
[2024-05-14T20:02:04.660+0000] {logging_mixin.py:188} INFO - [2024-05-14T20:02:04.655+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/DE_DP_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DE_DP_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-05-14T20:02:04.662+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/DE_DP_dag.py
[2024-05-14T20:02:04.689+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/DE_DP_dag.py took 0.066 seconds
[2024-05-14T20:02:34.825+0000] {processor.py:161} INFO - Started process (PID=228) to work on /opt/airflow/dags/DE_DP_dag.py
[2024-05-14T20:02:34.826+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/DE_DP_dag.py for tasks to queue
[2024-05-14T20:02:34.828+0000] {logging_mixin.py:188} INFO - [2024-05-14T20:02:34.827+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/DE_DP_dag.py
[2024-05-14T20:02:34.847+0000] {logging_mixin.py:188} INFO - [2024-05-14T20:02:34.843+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/DE_DP_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DE_DP_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-05-14T20:02:34.849+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/DE_DP_dag.py
[2024-05-14T20:02:34.876+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/DE_DP_dag.py took 0.057 seconds
[2024-05-14T20:03:05.015+0000] {processor.py:161} INFO - Started process (PID=233) to work on /opt/airflow/dags/DE_DP_dag.py
[2024-05-14T20:03:05.016+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/DE_DP_dag.py for tasks to queue
[2024-05-14T20:03:05.018+0000] {logging_mixin.py:188} INFO - [2024-05-14T20:03:05.018+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/DE_DP_dag.py
[2024-05-14T20:03:05.041+0000] {logging_mixin.py:188} INFO - [2024-05-14T20:03:05.036+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/DE_DP_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DE_DP_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-05-14T20:03:05.043+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/DE_DP_dag.py
[2024-05-14T20:03:05.071+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/DE_DP_dag.py took 0.062 seconds
[2024-05-14T20:03:35.211+0000] {processor.py:161} INFO - Started process (PID=238) to work on /opt/airflow/dags/DE_DP_dag.py
[2024-05-14T20:03:35.212+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/DE_DP_dag.py for tasks to queue
[2024-05-14T20:03:35.214+0000] {logging_mixin.py:188} INFO - [2024-05-14T20:03:35.214+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/DE_DP_dag.py
[2024-05-14T20:03:35.233+0000] {logging_mixin.py:188} INFO - [2024-05-14T20:03:35.229+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/DE_DP_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DE_DP_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-05-14T20:03:35.235+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/DE_DP_dag.py
[2024-05-14T20:03:35.262+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/DE_DP_dag.py took 0.058 seconds
[2024-05-14T20:04:05.394+0000] {processor.py:161} INFO - Started process (PID=243) to work on /opt/airflow/dags/DE_DP_dag.py
[2024-05-14T20:04:05.395+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/DE_DP_dag.py for tasks to queue
[2024-05-14T20:04:05.396+0000] {logging_mixin.py:188} INFO - [2024-05-14T20:04:05.396+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/DE_DP_dag.py
[2024-05-14T20:04:05.417+0000] {logging_mixin.py:188} INFO - [2024-05-14T20:04:05.412+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/DE_DP_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DE_DP_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-05-14T20:04:05.418+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/DE_DP_dag.py
[2024-05-14T20:04:05.447+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/DE_DP_dag.py took 0.059 seconds
[2024-05-14T20:04:35.584+0000] {processor.py:161} INFO - Started process (PID=248) to work on /opt/airflow/dags/DE_DP_dag.py
[2024-05-14T20:04:35.585+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/DE_DP_dag.py for tasks to queue
[2024-05-14T20:04:35.587+0000] {logging_mixin.py:188} INFO - [2024-05-14T20:04:35.586+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/DE_DP_dag.py
[2024-05-14T20:04:35.605+0000] {logging_mixin.py:188} INFO - [2024-05-14T20:04:35.600+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/DE_DP_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DE_DP_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-05-14T20:04:35.606+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/DE_DP_dag.py
[2024-05-14T20:04:35.633+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/DE_DP_dag.py took 0.055 seconds
[2024-05-14T20:05:05.770+0000] {processor.py:161} INFO - Started process (PID=253) to work on /opt/airflow/dags/DE_DP_dag.py
[2024-05-14T20:05:05.771+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/DE_DP_dag.py for tasks to queue
[2024-05-14T20:05:05.773+0000] {logging_mixin.py:188} INFO - [2024-05-14T20:05:05.772+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/DE_DP_dag.py
[2024-05-14T20:05:05.789+0000] {logging_mixin.py:188} INFO - [2024-05-14T20:05:05.786+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/DE_DP_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DE_DP_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-05-14T20:05:05.790+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/DE_DP_dag.py
[2024-05-14T20:05:05.816+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/DE_DP_dag.py took 0.051 seconds
[2024-05-14T20:05:35.956+0000] {processor.py:161} INFO - Started process (PID=258) to work on /opt/airflow/dags/DE_DP_dag.py
[2024-05-14T20:05:35.957+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/DE_DP_dag.py for tasks to queue
[2024-05-14T20:05:35.959+0000] {logging_mixin.py:188} INFO - [2024-05-14T20:05:35.959+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/DE_DP_dag.py
[2024-05-14T20:05:35.976+0000] {logging_mixin.py:188} INFO - [2024-05-14T20:05:35.972+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/DE_DP_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DE_DP_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-05-14T20:05:35.977+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/DE_DP_dag.py
[2024-05-14T20:05:36.002+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/DE_DP_dag.py took 0.051 seconds
[2024-05-14T20:06:06.136+0000] {processor.py:161} INFO - Started process (PID=263) to work on /opt/airflow/dags/DE_DP_dag.py
[2024-05-14T20:06:06.137+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/DE_DP_dag.py for tasks to queue
[2024-05-14T20:06:06.139+0000] {logging_mixin.py:188} INFO - [2024-05-14T20:06:06.138+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/DE_DP_dag.py
[2024-05-14T20:06:06.157+0000] {logging_mixin.py:188} INFO - [2024-05-14T20:06:06.153+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/DE_DP_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DE_DP_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-05-14T20:06:06.159+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/DE_DP_dag.py
[2024-05-14T20:06:06.185+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/DE_DP_dag.py took 0.055 seconds
[2024-05-14T20:06:36.364+0000] {processor.py:161} INFO - Started process (PID=268) to work on /opt/airflow/dags/DE_DP_dag.py
[2024-05-14T20:06:36.365+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/DE_DP_dag.py for tasks to queue
[2024-05-14T20:06:36.367+0000] {logging_mixin.py:188} INFO - [2024-05-14T20:06:36.367+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/DE_DP_dag.py
[2024-05-14T20:06:36.387+0000] {logging_mixin.py:188} INFO - [2024-05-14T20:06:36.382+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/DE_DP_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DE_DP_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-05-14T20:06:36.388+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/DE_DP_dag.py
[2024-05-14T20:06:36.415+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/DE_DP_dag.py took 0.057 seconds
[2024-05-14T20:07:06.537+0000] {processor.py:161} INFO - Started process (PID=273) to work on /opt/airflow/dags/DE_DP_dag.py
[2024-05-14T20:07:06.538+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/DE_DP_dag.py for tasks to queue
[2024-05-14T20:07:06.540+0000] {logging_mixin.py:188} INFO - [2024-05-14T20:07:06.539+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/DE_DP_dag.py
[2024-05-14T20:07:06.561+0000] {logging_mixin.py:188} INFO - [2024-05-14T20:07:06.555+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/DE_DP_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DE_DP_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-05-14T20:07:06.562+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/DE_DP_dag.py
[2024-05-14T20:07:06.589+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/DE_DP_dag.py took 0.058 seconds
[2024-05-14T20:07:36.740+0000] {processor.py:161} INFO - Started process (PID=278) to work on /opt/airflow/dags/DE_DP_dag.py
[2024-05-14T20:07:36.741+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/DE_DP_dag.py for tasks to queue
[2024-05-14T20:07:36.743+0000] {logging_mixin.py:188} INFO - [2024-05-14T20:07:36.742+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/DE_DP_dag.py
[2024-05-14T20:07:36.756+0000] {logging_mixin.py:188} INFO - [2024-05-14T20:07:36.753+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/DE_DP_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DE_DP_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-05-14T20:07:36.757+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/DE_DP_dag.py
[2024-05-14T20:07:36.784+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/DE_DP_dag.py took 0.050 seconds
[2024-05-14T20:08:06.914+0000] {processor.py:161} INFO - Started process (PID=283) to work on /opt/airflow/dags/DE_DP_dag.py
[2024-05-14T20:08:06.915+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/DE_DP_dag.py for tasks to queue
[2024-05-14T20:08:06.917+0000] {logging_mixin.py:188} INFO - [2024-05-14T20:08:06.916+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/DE_DP_dag.py
[2024-05-14T20:08:06.935+0000] {logging_mixin.py:188} INFO - [2024-05-14T20:08:06.931+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/DE_DP_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DE_DP_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-05-14T20:08:06.936+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/DE_DP_dag.py
[2024-05-14T20:08:06.962+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/DE_DP_dag.py took 0.054 seconds
[2024-05-14T20:08:37.114+0000] {processor.py:161} INFO - Started process (PID=288) to work on /opt/airflow/dags/DE_DP_dag.py
[2024-05-14T20:08:37.115+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/DE_DP_dag.py for tasks to queue
[2024-05-14T20:08:37.116+0000] {logging_mixin.py:188} INFO - [2024-05-14T20:08:37.116+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/DE_DP_dag.py
[2024-05-14T20:08:37.135+0000] {logging_mixin.py:188} INFO - [2024-05-14T20:08:37.131+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/DE_DP_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DE_DP_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-05-14T20:08:37.136+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/DE_DP_dag.py
[2024-05-14T20:08:37.162+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/DE_DP_dag.py took 0.054 seconds
[2024-05-14T20:09:07.284+0000] {processor.py:161} INFO - Started process (PID=293) to work on /opt/airflow/dags/DE_DP_dag.py
[2024-05-14T20:09:07.285+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/DE_DP_dag.py for tasks to queue
[2024-05-14T20:09:07.286+0000] {logging_mixin.py:188} INFO - [2024-05-14T20:09:07.286+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/DE_DP_dag.py
[2024-05-14T20:09:07.306+0000] {logging_mixin.py:188} INFO - [2024-05-14T20:09:07.301+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/DE_DP_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DE_DP_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-05-14T20:09:07.308+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/DE_DP_dag.py
[2024-05-14T20:09:07.330+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/DE_DP_dag.py took 0.052 seconds
[2024-05-14T20:09:37.482+0000] {processor.py:161} INFO - Started process (PID=298) to work on /opt/airflow/dags/DE_DP_dag.py
[2024-05-14T20:09:37.483+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/DE_DP_dag.py for tasks to queue
[2024-05-14T20:09:37.485+0000] {logging_mixin.py:188} INFO - [2024-05-14T20:09:37.484+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/DE_DP_dag.py
[2024-05-14T20:09:37.502+0000] {logging_mixin.py:188} INFO - [2024-05-14T20:09:37.498+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/DE_DP_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DE_DP_dag.py", line 5, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-05-14T20:09:37.503+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/DE_DP_dag.py
[2024-05-14T20:09:37.526+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/DE_DP_dag.py took 0.050 seconds
